singleuser:
  image:
    name: docker.io/escomp/test-ctsm-cislcloud-v4
    tag: "latest"
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 600m
    nginx.org/client-max-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: proxy-public
    nginx.org/websocket-services: proxy-public
    cert-manager.io/cluster-issuer: incommon
    ingressClassName: nginx
  hosts: 
    - ctsm-jhub.k8s.ucar.edu
  tls:
    - secretName: ctsm-jhub-tls-cert
      hosts:
        - ctsm-jhub.k8s.ucar.edu
hub:
  config:
    JupyterHub:
      authenticator_class: nativeauthenticator.NativeAuthenticator
    Authenticator:
      admin_users:
        - ncote
        - kcote
        - varshareddy
        - bdobbins
        - slevis
        - khrpcek
    NativeAuthenticator:
      enable_signup: true
      minimum_password_length: 8
      check_common_password: true
      ask_email_on_signup: true
      allowed_failed_logins: 3
      seconds_before_next_try: 1200